### ISSUE TITLE
Problems with some apps. 

### ISSUE THREAD

**Issue by mehmeteminkartal** [lperiodbose/youdownloadtheappanditdoesntwork#5]
Hi. I’ve checked the App Store guidelines and found that most of the apps listed on your website are exempt on rules below. I don’t support either sides on this whole controversy. I’m just saying people are going to point out to these rules and might call you out. 

I know these are a bit controversial topics right now. I don’t intend any hate or bad intentions. Just a fellow ios developer trying to help another ios dev. 

Pasting from app store guidelines
> 3.1.4 Hardware-Specific Content: In limited circumstances, such as when features are dependent upon specific hardware to function, the app may unlock that functionality without using in-app purchase (e.g. an astronomy app that adds features when synced with a telescope). App features that work in combination with an approved physical product (such as a toy) on an optional basis may unlock functionality without using in-app purchase, provided that an in-app purchase option is available as well. You may not, however, require users to purchase unrelated products or engage in advertising or marketing activities to unlock app functionality.

> 3.1.5(a) Goods and Services Outside of the App: If your app enables people to purchase goods or services that will be consumed outside of the app, you must use purchase methods other than in-app purchase to collect those payments, such as Apple Pay or traditional credit card entry.

**Comment by LannyBose** [comment]
Yep, I get that, which is why I named the site after the Schiller quote (whose standard is based on first-run functionality) and not a specific App Store guideline.

Though, I still have the question, why does Apple believe it gets 30% of the revenue of some businesses and not others? Why did they gerrymander the rules in this way?

There could be **ethical** or **philosophical** reasons why Apple believes it's entitled to Email service revenue and not digital movie rental. If so, I haven't heard them. From my vantage-point, as an indie SaaS developer, it seems far more rooted in business strategy and power dynamics than any purely technical or ethical reasoning.

Regardless, this is a conversation we should be having in public. Not in off-the-record calls with App Review or in whisper networks among developers.

Anyway, I appreciate the generosity of your comment and understand we're in a huge gray zone. Thanks for adding to the conversation!

**Comment by LannyBose** [comment]
I'm going to close the issue because nothing's explicitly "broken" here, and I'm happy to continue chatting! 😀
